name: Monthly EV-A71 Pipeline Run
on:
  workflow_dispatch:  # Manual trigger for testing
  schedule:
    - cron: '0 0 1 * *'  # 1st of month, midnight UTC
  push:
    branches: 
      - automatic-updates  # Only run on this branch

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: automatic-updates  # Explicitly checkout this branch

      - name: Checkout data repository
        uses: actions/checkout@v4
        with: 
          repository: hodcroftlab/nextstrain-builds-data
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: data-source

      - name: Copy EV-A71 data to correct location
        run:  |
          # Create data directory if it doesn't exist
          mkdir -p data
          
          # Copy all EV-A71-specific data
          if [ -d "data-source/enterovirus_a71" ]; then
            cp -r data-source/enterovirus_a71/* data/
            echo "EV-A71 data copied successfully"
          else
            echo "ERROR: enterovirus_a71 folder not found in nextstrain-builds-data"
            exit 1
          fi
          
          # Clean up temporary directory
          rm -rf data-source
          
          # Verify critical files exist before proceeding
          echo "Files in data/:"
          ls -lh data/
          
          # Check for required files
          required_files=("meta_public.tsv" "meta_collab.tsv" "subgenotypes_rivm.csv" "clades_vp1.tsv" "strain_names_previous_run.tsv")
          for file in "${required_files[@]}"; do
            if [ ! -f "data/$file" ]; then
              echo "⚠️  Warning: $file not found in data/"
            fi
          done

      - name:  Setup micromamba
        uses:  mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yaml
          environment-name: nextstrain
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'

      - name: Clean previous results
        run: |
          snakemake --cores 1 clean || echo "Clean completed"
        shell:  micromamba-shell {0}

      - name: Run full pipeline
        env:  
          REMOTE_GROUP: ${{ secrets.NEXTSTRAIN_REMOTE_GROUP }}
          ENTREZ_EMAIL: ${{ secrets.ENTREZ_EMAIL }}
        run: |
          snakemake --cores 10 next_update \
            --use-conda \
            --rerun-incomplete \
            --printshellcmds
        shell: micromamba-shell {0}

      - name:  Upload to Nextstrain
        if: success()
        env: 
          NEXTSTRAIN_USERNAME: ${{ secrets.NEXTSTRAIN_USERNAME }}
          NEXTSTRAIN_PASSWORD: ${{ secrets.NEXTSTRAIN_PASSWORD }}
          REMOTE_GROUP:  ${{ secrets.NEXTSTRAIN_REMOTE_GROUP }}
        run: |
          snakemake --cores 2 upload
        shell: micromamba-shell {0}

      - name:  Commit and Push Results
        if: success()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin automatic-updates
          git add auspice/ data/date_last_updated.txt data/local_accn.txt
          git commit -m "chore:  update EV-A71 builds [skip ci]" || echo "No changes to commit"
          git push origin automatic-updates
        shell: bash -l {0}

      - name: Upload workflow artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with: 
          name:  pipeline-results
          path: auspice/
          retention-days: 30